package com.company.hr.contract;

import au.com.dius.pact.provider.junit5.HttpTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.State;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import com.company.hr.model.entity.Employee;
import com.company.hr.model.entity.EmployeeRole;
import com.company.hr.repository.EmployeeRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

/**
 * Verifies the real controllers against the consumer pact generated by
 * frontend/src/api/__contract__/auth.pact.test.ts (SPEC.md "Testing Strategy" > Contract
 * Testing). Run via `mvn test -Dtest=PactProviderVerificationTest` — see
 * .github/workflows/ci.yml's contract-tests job, which generates the pact file first.
 *
 * Requires Docker (Testcontainers Postgres), same as ShiftSwapFlowIntegrationTest.
 */
@Provider("shiftswap-backend")
@PactFolder("../contract-tests/pacts")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("local")
@Testcontainers
class PactProviderVerificationTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine");

    @DynamicPropertySource
    static void datasourceProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", postgres::getJdbcUrl);
        registry.add("spring.datasource.username", postgres::getUsername);
        registry.add("spring.datasource.password", postgres::getPassword);
    }

    @LocalServerPort
    private int port;

    @Autowired
    private EmployeeRepository employeeRepository;

    @Autowired
    private PasswordEncoder passwordEncoder;

    @BeforeEach
    void setTarget(PactVerificationContext context) {
        context.setTarget(new HttpTestTarget("localhost", port));
    }

    @State("an active employee alice.employee@example.com exists with password password123")
    void activeEmployeeExists() {
        employeeRepository.findByEmailIgnoreCase("alice.employee@example.com")
                .orElseGet(() -> employeeRepository.save(Employee.builder()
                        .employeeCode("PACT-0001")
                        .fullName("Alice Employee")
                        .email("alice.employee@example.com")
                        .passwordHash(passwordEncoder.encode("password123"))
                        .role(EmployeeRole.EMPLOYEE)
                        .active(true)
                        .build()));
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void pactVerificationTestTemplate(PactVerificationContext context) {
        context.verifyInteraction();
    }
}
